############################
### LOCALHOST ###
############################

######## RESTAURANTS

### Gets all restaurants
GET http://localhost:3000/restaurants

### Gets a restaurant by its ID
GET http://localhost:3000/restaurants/62b39a41158ce93627c42dad

### Creates a restaurant
POST http://localhost:3000/restaurants HTTP/1.1 
content-type: application/json

{
  "restaurantName": "New name",
  "cuisine": "Brazilian",
  "description": "A brief description about the restaurant",
  "address": "274 S 2nd W, Rexburg, ID 83440",
  "zipCode": "13452",
  "opens": "10am",
  "closes": "9pm",
  "phoneNumber": "208-356-9005",
  "restaurantWebsite": "example.com",
  "reviews": [
    "1",
    "2",
    "3"
  ]
}

### Updates a restaurant
PUT http://localhost:3000/restaurants/62b39a41158ce93627c42dad HTTP/1.1 
content-type: application/json

{
  "restaurantName": "Other Name",
  "cuisine": "Whatever",
  "description": "A brief description about the restaurant",
  "address": "274 S 2nd W, Rexburg, ID 83440",
  "zipCode": "13452",
  "opens": "10am",
  "closes": "9pm",
  "phoneNumber": "208-356-9005",
  "restaurantWebsite": "example.com",
  "reviews": [
    "1",
    "2",
    "3"
  ]
}

### Gets restaurant that do not match such Zip Code
GET http://localhost:3000/restaurants/excludeByZipCode/12345

### Gets restaurant that do not match such Cuisine
GET http://localhost:3000/restaurants/excludeByCuisine/Mexican

### Deletes a restaurant by its ID
DELETE  http://localhost:3000/restaurants/62b3ac39c2f688521a6317be HTTP/1.1 



######## USERS

### get all users
GET http://localhost:3000/users

### get one user
GET http://localhost:3000/users/62b1d5f9ffeaf1c954d35580

### create a new user
POST http://localhost:3000/users HTTP/1.1 
content-type: application/json

{
  "name":"John",
  "reviewsPosted":[],
  "password":"123",
  "email":"email@email.com"
}

### update a user
PUT http://localhost:3000/users/62b32b21bfdce0a41f009702 HTTP/1.1
content-type: application/json

{
  "name":"John Smith",
  "reviewsPosted":[],
  "password":"123",
  "email":"email2@email.com"
  }
  
### delete a user
DELETE http://localhost:3000/users/62b32b21bfdce0a41f009702



######## CUISINES

### get all cuisines
GET http://localhost:3000/cuisines

### get one cuisine
GET http://localhost:3000/cuisines/62b1d9b8ffeaf1c954d35584

### create a new cuisine
POST http://localhost:3000/cuisines HTTP/1.1 
content-type: application/json

{
  "name":"Southern",
  "description":"Usually deap-fried and buttered, no one can beat a southern Grandma's chicken."
}

### update a cuisine
PUT http://localhost:3000/cuisines/62b32d17bfdce0a41f009704 HTTP/1.1
content-type: application/json

{
  "name":"Southern",
  "description":"Usually deap-fried."
  }
  
### delete a cuisine
DELETE http://localhost:3000/cuisines/62b32d17bfdce0a41f009704