############################
### LOCALHOST ###
############################

######## RESTAURANTS

GET http://localhost:3000/restaurants
###
GET http://localhost:3000/restaurants/62b1dd7e3e72bb0c1e8a07f3

###
POST http://localhost:3000/restaurants HTTP/1.1 
content-type: application/json

{
  "restaurantName": "New name",
  "cuisine": "Whatever",
  "description": "A brief description about the restaurant",
  "address": "274 S 2nd W, Rexburg, ID 83440",
  "zipCode": "12345",
  "opens": "10am",
  "closes": "9pm",
  "phoneNumber": "208-356-9005",
  "restaurantWebsite": "example.com",
  "reviews": [
    "1",
    "2",
    "3"
  ]
}

// USERS
### get all users
GET http://localhost:3000/users

### get one user
GET http://localhost:3000/users/62b1d5f9ffeaf1c954d35580

### create a new user
POST http://localhost:3000/users HTTP/1.1 
content-type: application/json

{
  "name":"John",
  "reviewsPosted":[],
  "password":"123",
  "email":"email@email.com"
}


### update a user
PUT http://localhost:3000/users/62b32b21bfdce0a41f009702 HTTP/1.1
content-type: application/json

{
  "name":"John Smith",
  "reviewsPosted":[],
  "password":"123",
  "email":"email2@email.com"
  }
  
  
### delete a user
DELETE http://localhost:3000/users/62b32b21bfdce0a41f009702

// CUISINES
### get all cuisines
GET http://localhost:3000/cuisines

### get one cuisine
GET http://localhost:3000/cuisines/62b1d9b8ffeaf1c954d35584

### create a new cuisine
POST http://localhost:3000/cuisines HTTP/1.1 
content-type: application/json

{
  "name":"Southern",
  "description":"Usually deap-fried and buttered, no one can beat a southern Grandma's chicken."
}


### update a cuisine
PUT http://localhost:3000/cuisines/62b32d17bfdce0a41f009704 HTTP/1.1
content-type: application/json

{
  "name":"Southern",
  "description":"Usually deap-fried."
  }
  
  
### delete a cuisine
DELETE http://localhost:3000/cuisines/62b32d17bfdce0a41f009704