############################
######## LOCALHOST #########
############################

######## RESTAURANTS

### Gets all restaurants
GET http://localhost:3000/restaurants

### Gets a restaurant by its ID
GET http://localhost:3000/restaurants/62ce4253a571bb73aef548b2

### Creates a restaurant
POST http://localhost:3000/restaurants HTTP/1.1 
content-type: application/json

{
  "restaurantName": "Mexican Restaurant 2",
  "cuisine": "62b9d03ba723d8b5d45f6a05",
  "description": "A brief description about the restaurant",
  "address": "274 S 2nd W, Rexburg, ID 83440",
  "zipCode": "12345",
  "opens": "10am",
  "closes": "9pm",
  "phoneNumber": "208-356-9005",
  "restaurantWebsite": "example.com",
  "imgUrl": "../pic.jpg"
}

### Updates a restaurant
PUT http://localhost:3000/restaurants/62ce4253a571bb73aef548b2 HTTP/1.1 
content-type: application/json

{
  "restaurantName": "Other Name",
  "cuisine": "62b9d03ba723d8b5d45f6a05",
  "description": "A brief description about the restaurant",
  "address": "274 S 2nd W, Rexburg, ID 83440",
  "zipCode": "13452",
  "opens": "10am",
  "closes": "9pm",
  "phoneNumber": "208-356-9005",
  "restaurantWebsite": "example.com",
  "imgUrl": "../other.jpg"
}

### Gets restaurant that do not match such Zip Code
GET http://localhost:3000/restaurants/excludeByZipCode/12345

### Gets restaurant that do not match such Cuisine
GET http://localhost:3000/restaurants/excludeByCuisine/Mexican

### Deletes a restaurant by its ID
DELETE  http://localhost:3000/restaurants/62ce458e5314790e046640bc HTTP/1.1 