############################
######## LOCALHOST #########
############################

######## REVIEWS

### Gets all reviews
GET http://localhost:3000/reviews

### Gets a review by its ID
GET http://localhost:3000/reviews/62b9e5715b60a18abcc2bb32

### Creates a review
POST http://localhost:3000/reviews HTTP/1.1 
content-type: application/json

{
  "postedBy": "62b9e29cc8da181ea71296d6",
  "restaurantId": "62b9d069a723d8b5d45f6a07",
  "content": "This is a review by Tanner about the Mexican restaurant"
}

### Updates a restaurant by its ID
PUT http://localhost:3000/reviews/62b3fca276e0fc20611878c6 HTTP/1.1 
content-type: application/json

{
  "postedBy": "User 3",
  "restaurantId": "3",
  "content": "This is another review"
}

### Deletes a review by its ID
DELETE http://localhost:3000/reviews/62b3fdb09840ef254b1869f4