############################
######## LOCALHOST #########
############################

######## USERS

### get all users
GET http://localhost:3000/users

### get one user
GET http://localhost:3000/users/62b9e26dc8da181ea71296d2

### create a new user
POST http://localhost:3000/users HTTP/1.1 
content-type: application/json

{
  "name":"Tanner",
  "password":"12345",
  "email":"tanner@tanner.com"
}

### update a user
PUT http://localhost:3000/users/62b32b21bfdce0a41f009702 HTTP/1.1
content-type: application/json

{
  "name":"John Smith",
  "password":"123",
  "email":"email2@email.com"
  }
  
### delete a user
DELETE http://localhost:3000/users/62b32b21bfdce0a41f009702